#!/usr/bin/with-contenv bash

# make folder
mkdir -p \
	/config/argus

# initialise env file
if [ ! -f "/config/argus/env" ]; then
	cp /defaults/env /config/argus/env
	cd /usr/share/webapps/argus || exit
	[[ -f /usr/share/webapps/argus/.env || -L /usr/share/webapps/argus/.env ]] && \
		rm /usr/share/webapps/argus/.env
	ln -s /config/argus/env /usr/share/webapps/argus/.env
	php artisan key:generate
fi

# remake symlink for env
[[ -f /usr/share/webapps/argus/.env ]] && \
	rm /usr/share/webapps/argus/.env
[[ ! -L /usr/share/webapps/argus/.env ]] && \
	ln -s /config/argus/env /usr/share/webapps/argus/.env

# symlink for database
[[ ! -f /config/argus/database.sqlite ]] && \
	touch /config/argus/database.sqlite
[[ -f /usr/share/webapps/argus/database/database.sqlite ]] && \
	rm /usr/share/webapps/argus/database/database.sqlite
[[ ! -L /usr/share/webapps/argus/database/database.sqlite ]] && \
	ln -s /config/argus/database.sqlite /usr/share/webapps/argus/database/database.sqlite

# permissions
chown -R abc:abc \
	/config/argus \
	/usr/share/webapps/argus
